apiVersion: apps/v1
kind: Deployment
metadata:
  name: filefighter-db-deployment
  labels:
    app: filefighter
spec:
  selector:
    matchLabels:
      app: filefighter-db
  template:
    metadata:
      labels:
        app: filefighter-db
    spec:
      containers:
        - name: ff-db
          image: mongo:latest # https://hub.docker.com/_/mongo
          env:
            - name: MONGO_INITDB
              value: "filefighter"
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "root"
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ff-secret
                  key: password
          ports:
            - containerPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: ff-db-service
spec:
  selector:
    app: filefighter-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017