apiVersion: apps/v1
kind: Deployment
metadata:
  name: filefighter-fe-deployment
  labels:
    app: filefighter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: filefighter-fe
  template: # describes the pods
    metadata:
      labels:
        app: filefighter-fe
    spec:
      containers:
      - name: ff-frontend
        image: filefighter/frontend # https://hub.docker.com/r/filefighter/frontend
        env:                        # https://github.com/FileFighter/WebApp/blob/master/webapp_provider/dockerfile
          - name: REST_PORT
            value: "7080"
        ports:
        - containerPort: 5000       # as exposed in the Dockerfile

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: filefighter-rest-deployment
  labels:
    app: filefighter
spec:
  selector:
    matchLabels:
      app: filefighter-rest
  template:
    metadata:
      labels:
        app: filefighter-rest
    spec:
      containers:
      - name: ff-rest
        image: filefighter/rest
        env:
          - name: DB_USERNAME
            value: "root"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ff-secret
                key: password
          - name: DB_NAME
            value: "filefighter"
          - name: DB_CONTAINER_NAME
            value: "ff-db-service"
          - name: SPRING_PROFILES_ACTIVE
            value: "prod"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 3
        ports:
        - containerPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: filefighter-db-deployment
  labels:
    app: filefighter
spec:
  selector:
    matchLabels:
      app: filefighter-db
  template:
    metadata:
      labels:
        app: filefighter-db
    spec:
      containers:
        - name: ff-db
          image: mongo:latest
          env:
            - name: MONGO_INITDB
              value: "filefighter"
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "root"
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ff-secret
                  key: password
          ports:
            - containerPort: 27017