apiVersion: apps/v1
kind: Deployment
metadata:
  name: filefighter-fe-deployment
  labels:
    app: filefighter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: filefighter-fe
  template: # describes the pods
    metadata:
      labels:
        app: filefighter-fe
    spec:
      containers:
        - name: ff-frontend
          image: filefighter/frontend # https://hub.docker.com/r/filefighter/frontend
          env:                        # https://github.com/FileFighter/WebApp/blob/master/webapp_provider/dockerfile
            - name: REST_PORT
              value: "7080"
          ports:
            - containerPort: 5000       # as exposed in the Dockerfile

---

apiVersion: v1
kind: Service
metadata:
  name: ff-fe-service
spec:
  selector:
    app: filefighter-fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
