apiVersion: v1
kind: Service
metadata:
  name: ff-fe-service
spec:
  selector:
    app: filefighter-fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
      
---

apiVersion: v1
kind: Service
metadata:
  name: ff-rest-service
spec:
  selector:
    app: filefighter-rest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: ff-db-service
spec:
  selector:
    app: filefighter-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017